[package]
name = "cw721"
version = "0.0.1"
authors = ["Dom Steil <dom@stateset.io>"]
edition = "2021"
description = "Stateset Interface: cw721"
license = "Apache-2.0"
repository = "https://github.com/stateset/stateset-contracts"

[dependencies]
cw-storage-plus = "0.13.2"
cosmwasm-std = { version = "1.0.0-beta8" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.0.0-beta8" }
